[tool.poetry]
name = "zycelium-zygote"
version = "0.0.1"
description = "Zycelium Framework"
authors = ["Harshad Sharma <harshad@sharma.io>"]
license = "BSD 3-Clause License"
readme = "README.md"
packages = [{include = "zycelium", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
rumps = "^0.4.0"
quart = "^0.18.3"
quart-cors = "^0.6.0"
python-socketio = "^5.8.0"
click = "^8.1.3"
uvicorn = "^0.21.1"
APScheduler = "^3.10.1"
async-signals = "^0.1.5"
aiohttp = "^3.8.4"
sunnyside = "^2.0.0"
requests = "^2.28.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
pytest-asyncio = "^0.21.0"
black = "^23.3.0"
py2app = "^0.28.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
