"""
This is a setup.py script generated by py2applet

Usage:
    rm -rf {dist,build} && python setup.py py2app
"""

from setuptools import setup

APP_NAME = "Zygote"
APP_ICON = "images/icon.icns"

APP = ["zycelium_zygote.py"]

DATA_FILES = [
    ("images", [APP_ICON, "images/icon.png"]),
]

OPTIONS = {
    "iconfile": APP_ICON,
    "argv_emulation": True,
    "plist": {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleGetInfoString": APP_NAME,
        "CFBundleIdentifier": "com.zycelium.zygote",
        "CFBundleShortVersionString": "0.0.1",
        "LSUIElement": True,
    },
    "packages": [
        "rumps",
        "uvicorn",
        "quart",
    ],
}

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
    install_requires=["rumps"],
)
